In [2]:
import pandas as pd

## Topics in Part 2:
### Indexes: How to Set, Reset and use Indexes
### Filtering: Using Conditionals to Filter Rows and Columns
# ---------------------------------------------------------

Indexes: How to Set, Reset and Use Indexes

In [3]:
df = pd.read_json('./data.json')

df

    id                                  name                author  year
0    1                     The Space Odyssey      Arthur C. Clarke  2020
1    2                                  Dune         Frank Herbert  2020
2    3                           Neuromancer        William Gibson  2020
3    4                            Snow Crash       Neal Stephenson  2020
4    5             The Left Hand of Darkness     Ursula K. Le Guin  2020
5    6                            Foundation          Isaac Asimov  2020
6    7                              Hyperion           Dan Simmons  2020
7    8                       Brave New World         Aldous Huxley  2020
8    9                          Ender's Game      Orson Scott Card  2020
9   10                        Altered Carbon     Richard K. Morgan  2020
10  11  The Hitchhiker's Guide to the Galaxy         Douglas Adams  2020
11  12          The Expanse: Leviathan Wakes      James S.A. Corey  2020
12  13                              I, Robot          Isaac Asimov  2020
13  14                           The Martian             Andy Weir  2020
14  15                     Starship Troopers    Robert A. Heinlein  2020
15  16                The Three-Body Problem             Liu Cixin  2020
16  17  Do Androids Dream of Electric Sheep?        Philip K. Dick  2020
17  18                      The Time Machine            H.G. Wells  2020
18  19                      The Hunger Games       Suzanne Collins  2020
19  20                 The War of the Worlds            H.G. Wells  2020
20  21                   Alita: Battle Angel        Yukito Kishiro  2020
21  22                         Jurassic Park      Michael Crichton  2020
22  23                               Contact            Carl Sagan  2020
23  24                       The Windup Girl      Paolo Bacigalupi  2020
24  25                      The Fifth Season          N.K. Jemisin  2020
25  26                           Dark Matter          Blake Crouch  2020
26  27                              Red Mars  Kim Stanley Robinson  2020
27  28                   The Handmaid's Tale       Margaret Atwood  2020
28  29                         Old Man's War           John Scalzi  2020
29  30                               Kindred     Octavia E. Butler  2020
30  31                               Lock In           John Scalzi  2020
31  32                      The Dispossessed     Ursula K. Le Guin  2020
32  33                         The Leftovers          Tom Perrotta  2020
33  34                        Oryx and Crake       Margaret Atwood  2020
34  35                   The City & The City        China Mi√©ville  2020
35  36                              The Road       Cormac McCarthy  2020
36  37                             The Stand          Stephen King  2020
37  38                  The Andromeda Strain      Michael Crichton  2020

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      38 non-null     int64
 1   name    38 non-null     object
 2   author  38 non-null     object
 3   year    38 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.3+ KB

In [5]:
df['author']

0         Arthur C. Clarke
1            Frank Herbert
2           William Gibson
3          Neal Stephenson
4        Ursula K. Le Guin
5             Isaac Asimov
6              Dan Simmons
7            Aldous Huxley
8         Orson Scott Card
9        Richard K. Morgan
10           Douglas Adams
11        James S.A. Corey
12            Isaac Asimov
13               Andy Weir
14      Robert A. Heinlein
15               Liu Cixin
16          Philip K. Dick
17              H.G. Wells
18         Suzanne Collins
19              H.G. Wells
20          Yukito Kishiro
21        Michael Crichton
22              Carl Sagan
23        Paolo Bacigalupi
24            N.K. Jemisin
25            Blake Crouch
26    Kim Stanley Robinson
27         Margaret Atwood
28             John Scalzi
29       Octavia E. Butler
30             John Scalzi
31       Ursula K. Le Guin
32            Tom Perrotta
33         Margaret Atwood
34          China Mi√©ville
35         Cormac McCarthy
36            Stephen King
37        Michael Crichton
Name: author, dtype: object

In [11]:
df.set_index('author', inplace=True)
df.head()

                   id                       name  year
author
Arthur C. Clarke    1          The Space Odyssey  2020
Frank Herbert       2                       Dune  2020
William Gibson      3                Neuromancer  2020
Neal Stephenson     4                 Snow Crash  2020
Ursula K. Le Guin   5  The Left Hand of Darkness  2020

In [7]:
df.index

Index(['Arthur C. Clarke', 'Frank Herbert', 'William Gibson',
       'Neal Stephenson', 'Ursula K. Le Guin', 'Isaac Asimov', 'Dan Simmons',
       'Aldous Huxley', 'Orson Scott Card', 'Richard K. Morgan',
       'Douglas Adams', 'James S.A. Corey', 'Isaac Asimov', 'Andy Weir',
       'Robert A. Heinlein', 'Liu Cixin', 'Philip K. Dick', 'H.G. Wells',
       'Suzanne Collins', 'H.G. Wells', 'Yukito Kishiro', 'Michael Crichton',
       'Carl Sagan', 'Paolo Bacigalupi', 'N.K. Jemisin', 'Blake Crouch',
       'Kim Stanley Robinson', 'Margaret Atwood', 'John Scalzi',
       'Octavia E. Butler', 'John Scalzi', 'Ursula K. Le Guin', 'Tom Perrotta',
       'Margaret Atwood', 'China Mi√©ville', 'Cormac McCarthy', 'Stephen King',
       'Michael Crichton'],
      dtype='object', name='author')

In [8]:
df.columns

Index(['id', 'name', 'year'], dtype='object')

In [9]:
df.loc['Frank Herbert', 'name']

'Dune'

In [10]:
df.reset_index(inplace=True)

Filtering: Using Conditionals to Filter Rows and Columns

In [12]:
df.head()

                   id                       name  year
author
Arthur C. Clarke    1          The Space Odyssey  2020
Frank Herbert       2                       Dune  2020
William Gibson      3                Neuromancer  2020
Neal Stephenson     4                 Snow Crash  2020
Ursula K. Le Guin   5  The Left Hand of Darkness  2020

In [18]:
filt = (df['name'] == 'Dune') & (df['year'] == 2020)

In [19]:
df[filt]

               id  name  year
author
Frank Herbert   2  Dune  2020

In [21]:
df.loc[-filt]

                      id                                  name  year
author
Arthur C. Clarke       1                     The Space Odyssey  2020
William Gibson         3                           Neuromancer  2020
Neal Stephenson        4                            Snow Crash  2020
Ursula K. Le Guin      5             The Left Hand of Darkness  2020
Isaac Asimov           6                            Foundation  2020
Dan Simmons            7                              Hyperion  2020
Aldous Huxley          8                       Brave New World  2020
Orson Scott Card       9                          Ender's Game  2020
Richard K. Morgan     10                        Altered Carbon  2020
Douglas Adams         11  The Hitchhiker's Guide to the Galaxy  2020
James S.A. Corey      12          The Expanse: Leviathan Wakes  2020
Isaac Asimov          13                              I, Robot  2020
Andy Weir             14                           The Martian  2020
Robert A. Heinlein    15                     Starship Troopers  2020
Liu Cixin             16                The Three-Body Problem  2020
Philip K. Dick        17  Do Androids Dream of Electric Sheep?  2020
H.G. Wells            18                      The Time Machine  2020
Suzanne Collins       19                      The Hunger Games  2020
H.G. Wells            20                 The War of the Worlds  2020
Yukito Kishiro        21                   Alita: Battle Angel  2020
Michael Crichton      22                         Jurassic Park  2020
Carl Sagan            23                               Contact  2020
Paolo Bacigalupi      24                       The Windup Girl  2020
N.K. Jemisin          25                      The Fifth Season  2020
Blake Crouch          26                           Dark Matter  2020
Kim Stanley Robinson  27                              Red Mars  2020
Margaret Atwood       28                   The Handmaid's Tale  2020
John Scalzi           29                         Old Man's War  2020
Octavia E. Butler     30                               Kindred  2020
John Scalzi           31                               Lock In  2020
Ursula K. Le Guin     32                      The Dispossessed  2020
Tom Perrotta          33                         The Leftovers  2020
Margaret Atwood       34                        Oryx and Crake  2020
China Mi√©ville        35                   The City & The City  2020
Cormac McCarthy       36                              The Road  2020
Stephen King          37                             The Stand  2020
Michael Crichton      38                  The Andromeda Strain  2020

In [24]:
high_id = (df['id'] >= 25) & (df['id'] <= 30)

In [25]:
df[high_id]

                      id                 name  year
author
N.K. Jemisin          25     The Fifth Season  2020
Blake Crouch          26          Dark Matter  2020
Kim Stanley Robinson  27             Red Mars  2020
Margaret Atwood       28  The Handmaid's Tale  2020
John Scalzi           29        Old Man's War  2020
Octavia E. Butler     30              Kindred  2020

In [26]:
df.loc[high_id, ['name', 'year']]

                                     name  year
author
N.K. Jemisin             The Fifth Season  2020
Blake Crouch                  Dark Matter  2020
Kim Stanley Robinson             Red Mars  2020
Margaret Atwood       The Handmaid's Tale  2020
John Scalzi                 Old Man's War  2020
Octavia E. Butler                 Kindred  2020

In [31]:
args = ['Red Mars', 'Kindred', 'Dark Matter']
search = (df['name'].isin(args))

In [34]:
df.loc[search, ['name', 'year']]

                             name  year
author
Blake Crouch          Dark Matter  2020
Kim Stanley Robinson     Red Mars  2020
Octavia E. Butler         Kindred  2020

In [35]:
containFilter = df['name'].str.contains('Dark', na=False)
containFilter

author
Arthur C. Clarke        False
Frank Herbert           False
William Gibson          False
Neal Stephenson         False
Ursula K. Le Guin        True
Isaac Asimov            False
Dan Simmons             False
Aldous Huxley           False
Orson Scott Card        False
Richard K. Morgan       False
Douglas Adams           False
James S.A. Corey        False
Isaac Asimov            False
Andy Weir               False
Robert A. Heinlein      False
Liu Cixin               False
Philip K. Dick          False
H.G. Wells              False
Suzanne Collins         False
H.G. Wells              False
Yukito Kishiro          False
Michael Crichton        False
Carl Sagan              False
Paolo Bacigalupi        False
N.K. Jemisin            False
Blake Crouch             True
Kim Stanley Robinson    False
Margaret Atwood         False
John Scalzi             False
Octavia E. Butler       False
John Scalzi             False
Ursula K. Le Guin       False
Tom Perrotta            False
Margaret Atwood         False
China Mi√©ville          False
Cormac McCarthy         False
Stephen King            False
Michael Crichton        False
Name: name, dtype: bool

In [37]:
df.loc[containFilter]

                   id                       name  year
author
Ursula K. Le Guin   5  The Left Hand of Darkness  2020
Blake Crouch       26                Dark Matter  2020

In [38]:
df.loc[containFilter, 'name']

author
Ursula K. Le Guin    The Left Hand of Darkness
Blake Crouch                       Dark Matter
Name: name, dtype: object